name: Deploy to master

on:
  push:
    branches: [ master ]

jobs:
  On-merge-to-master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Dispatch version notification to dependent docker acs repository
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ANLIXBOT_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/anlix-io/docker-genieacs/actions/workflows/dispatch.yml/dispatches \
            -d '{"ref": "master"}'
